/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as PatientsPatientIdLocationRouteImport } from './routes/patients_.$patientId.location'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdLocationRoute =
  PatientsPatientIdLocationRouteImport.update({
    id: '/patients_/$patientId/location',
    path: '/patients/$patientId/location',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/$patientId/location': typeof PatientsPatientIdLocationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/$patientId/location': typeof PatientsPatientIdLocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients_/$patientId/location': typeof PatientsPatientIdLocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/doctors'
    | '/login'
    | '/settings'
    | '/patients/$patientId'
    | '/patients/$patientId/location'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/doctors'
    | '/login'
    | '/settings'
    | '/patients/$patientId'
    | '/patients/$patientId/location'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/doctors'
    | '/login'
    | '/settings'
    | '/patients/$patientId'
    | '/patients_/$patientId/location'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DoctorsRoute: typeof DoctorsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsPatientIdLocationRoute: typeof PatientsPatientIdLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients_/$patientId/location': {
      id: '/patients_/$patientId/location'
      path: '/patients/$patientId/location'
      fullPath: '/patients/$patientId/location'
      preLoaderRoute: typeof PatientsPatientIdLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DoctorsRoute: DoctorsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsPatientIdLocationRoute: PatientsPatientIdLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
